=== svn2github/CLDR/trunk/LocaleElements.dtd
<!ELEMENT Abbreviation ( #PCDATA ) >

<!ELEMENT Address ( #PCDATA ) >

<!ELEMENT AddressFormat ( PostalPattern ) >

<!ELEMENT Application ( #PCDATA ) >

<!ELEMENT Audience ( #PCDATA ) >

<!ELEMENT Contact ( #PCDATA ) >

<!ELEMENT CountryCar ( #PCDATA ) >

<!ELEMENT CountryISBNNumber ( #PCDATA ) >

<!ELEMENT CountryNumber ( #PCDATA ) >

<!ELEMENT CountryPost ( #PCDATA ) >

<!ELEMENT Date ( #PCDATA ) >

<!ELEMENT DomesticPattern ( #PCDATA ) >

<!ELEMENT Email ( #PCDATA ) >

<!ELEMENT Fax ( #PCDATA ) >

<!ELEMENT GeneralSalutation ( #PCDATA ) >

<!ELEMENT Height ( #PCDATA ) >

<!ELEMENT Identification ( Title| Source| Address| Contact| Email| Telephone| Fax| Language| Territory| Audience| Application| Abbreviation| Revision| Date )* >

<!ELEMENT InternationalDialCode ( #PCDATA ) >

<!ELEMENT InternationalPattern ( #PCDATA ) >

<!ELEMENT InternationalPrefix ( #PCDATA ) >

<!ELEMENT Language ( #PCDATA ) >

<!ELEMENT LanguageLibraryUse ( #PCDATA ) >

<!ELEMENT LongSalutationMiss ( #PCDATA ) >

<!ELEMENT LongSalutationMr ( #PCDATA ) >

<!ELEMENT LongSalutationMrs ( #PCDATA ) >

<!ELEMENT NameFormat ( NamePattern| GeneralSalutation| ShortSalutationMr| ShortSalutationMiss|ShortSalutationMrs| LongSalutationMr| LongSalutationMiss| LongSalutationMrs )* >

<!ELEMENT NamePattern ( #PCDATA ) >

<!ELEMENT PaperSize ( Height, Width, Units ) >

<!ELEMENT PosixCompatibilityData ( messages| AddressFormat| NameFormat| Identification| TelephoneFormat )* >

<!ELEMENT PostalPattern ( #PCDATA ) >

<!ELEMENT Revision ( #PCDATA ) >

<!ELEMENT ShortSalutationMiss ( #PCDATA ) >

<!ELEMENT ShortSalutationMr ( #PCDATA ) >

<!ELEMENT ShortSalutationMrs ( #PCDATA ) >

<!ELEMENT Source ( #PCDATA ) >

<!ELEMENT Telephone ( #PCDATA ) >

<!ELEMENT TelephoneFormat ( InternationalPattern| DomesticPattern| InternationalDialCode| InternationalPrefix )* >

<!ELEMENT Territory ( #PCDATA ) >

<!ELEMENT Title ( #PCDATA ) >

<!ELEMENT Units ( #PCDATA ) >

<!ELEMENT Width ( #PCDATA ) >

<!ELEMENT after ( #PCDATA ) >

<!ELEMENT normalization ( #PCDATA ) >

<!ELEMENT alternate ( #PCDATA ) >

<!ELEMENT vairableTop ( #PCDATA ) >

<!ELEMENT caseLevel ( #PCDATA ) >

<!ELEMENT caseFirst ( #PCDATA ) >

<!ELEMENT composition ( #PCDATA ) >

<!ELEMENT lt1 ( #PCDATA ) >

<!ELEMENT am ( #PCDATA ) >

<!ELEMENT boundaries ( grapheme| word| Sentence| Line )* >

<!ELEMENT TransliteratorNamePattern ( #PCDATA ) >

<!ELEMENT calendar ( am | dayAbbr | dayNames | eras | monthAbbr | monthNames | patterns | pm | week |firstDay |minDays )* >
<!ATTLIST calendar class NMTOKEN #REQUIRED >
<!ATTLIST calendar default NMTOKEN #IMPLIED >
<!ATTLIST calendar inheritsFrom NMTOKEN #IMPLIED >

<!ELEMENT calendars ( calendar+ ) >

<!ELEMENT chars ( #PCDATA ) >

<!ELEMENT city ( #PCDATA ) >

<!ELEMENT collation ( collationElements ) >
<!ATTLIST collation accentOrder NMTOKEN #REQUIRED >
<!ATTLIST collation override NMTOKEN #REQUIRED >
<!ATTLIST collation version NMTOKEN #REQUIRED >


<!ELEMENT collationElements ( after | eq | gt1 | gt2 | gt3 | normalization | alternate | vairableTop | caseLevel | caseFirst | lt1)* >

<!ELEMENT correspondsTo ( #PCDATA ) >
<!ATTLIST correspondsTo vendor NMTOKEN #REQUIRED >

<!ELEMENT countries ( country+ ) >

<!ELEMENT country ( #PCDATA ) >
<!ATTLIST country id NMTOKEN #REQUIRED >
<!ATTLIST country iso2 NMTOKEN #IMPLIED >
<!ATTLIST country iso3 NMTOKEN #IMPLIED >

<!ELEMENT currencies ( currency+ ) >

<!ELEMENT currency ( symbol| pattern| decimal| name |group )* >
<!ATTLIST currency default NMTOKEN #IMPLIED >
<!ATTLIST currency id NMTOKEN #REQUIRED >

<!ELEMENT name ( #PCDATA ) >

<!ELEMENT date ( full| long| medium| short )* >

<!ELEMENT dateTime ( #PCDATA ) >

<!ELEMENT day ( #PCDATA ) >
<!ATTLIST day id NMTOKEN #IMPLIED >

<!ELEMENT dayAbbr ( day+ ) >

<!ELEMENT dayNames ( day+ ) >

<!ELEMENT daylight ( #PCDATA ) >

<!ELEMENT decimal ( #PCDATA ) >

<!ELEMENT displayNames ( scripts| languages| countries| variants |localePatterns )* >

<!ELEMENT encodings ( mapping+ ) >
<!ATTLIST encodings requiredLetters NMTOKEN #REQUIRED >

<!ELEMENT eq ( #PCDATA ) >

<!ELEMENT era ( #PCDATA ) >
<!ATTLIST era id NMTOKEN #REQUIRED >

<!ELEMENT eras ( era+ ) >

<!ELEMENT exponential ( #PCDATA ) >

<!ELEMENT firstDay ( #PCDATA ) >

<!ELEMENT full ( #PCDATA ) >

<!ELEMENT generic ( #PCDATA ) >

<!ELEMENT grapheme ( #PCDATA ) >
<!ATTLIST grapheme class NMTOKEN #REQUIRED >

<!ELEMENT group ( #PCDATA ) >

<!ELEMENT gt1 ( #PCDATA ) >

<!ELEMENT gt2 ( #PCDATA ) >

<!ELEMENT gt3 ( #PCDATA ) >

<!ELEMENT identity ( language| country| variant| correspondsTo )* >

<!ELEMENT infinity ( #PCDATA ) >

<!ELEMENT language ( #PCDATA ) >
<!ATTLIST language id NMTOKEN #REQUIRED >
<!ATTLIST language iso2 NMTOKEN #IMPLIED >
<!ATTLIST language iso3 NMTOKEN #IMPLIED >

<!ELEMENT languages ( language+ ) >

<!ELEMENT list ( #PCDATA ) >

<!ELEMENT locale ( #PCDATA ) >

<!ELEMENT localeData ( versioning | identity| orientation| encodings| displayNames | calendars | numberFormat | currencies | collation | timeZoneNames | boundaries | measurement | CountryPost | CountryNumber | CountryCar | CountryISBNNumber | LanguageLibraryUse | PaperSize | PosixCompatibilityData|TransliteratorNamePattern )* >

<!ELEMENT localePatterns ( locale, list, composition ) >

<!ELEMENT long ( #PCDATA | daylight | generic | standard )* >

<!ELEMENT mapping ( #PCDATA ) >
<!ATTLIST mapping name NMTOKEN #REQUIRED >

<!ELEMENT measurement ( #PCDATA ) >

<!ELEMENT medium ( #PCDATA ) >

<!ELEMENT messages ( no| yes| shortYes| shortNo )* >

<!ELEMENT minDays ( #PCDATA ) >

<!ELEMENT minusSign ( #PCDATA ) >

<!ELEMENT month ( #PCDATA ) >
<!ATTLIST month id NMTOKEN #REQUIRED >

<!ELEMENT monthAbbr ( month+ ) >

<!ELEMENT monthNames ( month+ ) >

<!ELEMENT nan ( #PCDATA ) >

<!ELEMENT nativeZeroDigit ( #PCDATA ) >

<!ELEMENT no ( #PCDATA ) >

<!ELEMENT numberFormat ( patterns| symbols )* >
<!ATTLIST numberFormat class NMTOKEN #REQUIRED >
<!ATTLIST numberFormat default NMTOKEN #REQUIRED >

<!ELEMENT orientation ( #PCDATA ) >
<!ATTLIST orientation characters NMTOKEN #REQUIRED >
<!ATTLIST orientation lines NMTOKEN #REQUIRED >

<!ELEMENT pattern ( #PCDATA ) >

<!ELEMENT patternDigit ( #PCDATA ) >

<!ELEMENT patterns ( chars| time| date| dateTime?| decimal?| percent?| scientific? )* >

<!ELEMENT perMille ( #PCDATA ) >

<!ELEMENT percent ( #PCDATA ) >

<!ELEMENT percentSign ( #PCDATA ) >

<!ELEMENT plusSign ( #PCDATA ) >

<!ELEMENT pm ( #PCDATA ) >

<!ELEMENT scientific ( #PCDATA ) >

<!ELEMENT script ( #PCDATA ) >
<!ATTLIST script id NMTOKEN #REQUIRED >

<!ELEMENT scripts ( script+ ) >

<!ELEMENT short ( #PCDATA | daylight | generic | standard )* >

<!ELEMENT shortNo ( #PCDATA ) >

<!ELEMENT shortYes ( #PCDATA ) >

<!ELEMENT standard ( #PCDATA ) >

<!ELEMENT symbol ( #PCDATA ) >

<!ELEMENT symbols ( decimal, group, list, percentSign, nativeZeroDigit, patternDigit, plusSign, minusSign, exponential, perMille, infinity, nan )* >

<!ELEMENT time ( #PCDATA | full | long | medium | short )* >

<!ELEMENT timeZoneNames ( zone+ ) >

<!ELEMENT variant ( #PCDATA ) >
<!ATTLIST variant id NMTOKEN #REQUIRED >

<!ELEMENT variants ( variant ) >

<!ELEMENT version ( #PCDATA ) >
<!ATTLIST version date CDATA #IMPLIED>
<!ATTLIST version number NMTOKEN #REQUIRED >

<!ELEMENT versioning ( version+ ) >

<!ELEMENT week ( minDays, firstDay, weekendStart, weekendEnd ) >

<!ELEMENT weekendEnd ( day, time ) >

<!ELEMENT weekendStart ( day, time ) >

<!ELEMENT word ( #PCDATA ) >
<!ATTLIST word class NMTOKEN #REQUIRED >

<!ELEMENT Line ( #PCDATA ) >
<!ATTLIST Line class NMTOKEN #REQUIRED >

<!ELEMENT Sentence ( #PCDATA ) >
<!ATTLIST Sentence class NMTOKEN #REQUIRED >

<!ELEMENT yes ( #PCDATA ) >

<!ELEMENT zone ( city | long | short )* >
<!ATTLIST zone default NMTOKEN #IMPLIED >
<!ATTLIST zone id CDATA #REQUIRED >
<!ELEMENT iso14652:iso14652  ( iso14652:messages| iso14652:AddressFormat| iso14652:NameFormat| iso14652:Identification| iso14652:TelephoneFormat )* >

<!ELEMENT iso14652:messages ( iso14652:no| iso14652:yes| iso14652:shortYes| iso14652:shortNo )* >
<!ELEMENT iso14652:no ( #PCDATA ) >
<!ELEMENT iso14652:yes ( #PCDATA ) >
<!ELEMENT iso14652:shortYes ( #PCDATA ) >
<!ELEMENT iso14652:shortNo ( #PCDATA ) >

<!ELEMENT iso14652:AddressFormat ( iso14652:PostalPattern ) >
<!ELEMENT iso14652:PostalPattern ( #PCDATA ) >

<!ELEMENT iso14652:NameFormat ( iso14652:NamePattern| iso14652:GeneralSalutation| iso14652:ShortSalutationMr| iso14652:ShortSalutationMiss|iso14652:ShortSalutationMrs| iso14652:LongSalutationMr| iso14652:LongSalutationMiss| iso14652:LongSalutationMrs )* >
<!ELEMENT iso14652:NamePattern ( #PCDATA ) >
<!ELEMENT iso14652:GeneralSalutation ( #PCDATA ) >
<!ELEMENT iso14652:ShortSalutationMr ( #PCDATA ) >
<!ELEMENT iso14652:ShortSalutationMiss ( #PCDATA ) >
<!ELEMENT iso14652:ShortSalutationMrs ( #PCDATA ) >
<!ELEMENT iso14652:LongSalutationMr ( #PCDATA ) >
<!ELEMENT iso14652:LongSalutationMiss ( #PCDATA ) >
<!ELEMENT iso14652:LongSalutationMrs ( #PCDATA ) >

<!ELEMENT iso14652:Identification ( iso14652:Title| iso14652:Source| iso14652:Address| iso14652:Contact| iso14652:Email| iso14652:Telephone| iso14652:Fax| iso14652:Language| iso14652:Territory| iso14652:Audience| iso14652:Application| iso14652:Abbreviation| iso14652:Revision| iso14652:Date )* >
<!ELEMENT iso14652:Title ( #PCDATA ) >
<!ELEMENT iso14652:Source ( #PCDATA ) >
<!ELEMENT iso14652:Address ( #PCDATA ) >
<!ELEMENT iso14652:Contact ( #PCDATA ) >
<!ELEMENT iso14652:Email ( #PCDATA ) >
<!ELEMENT iso14652:Telephone ( #PCDATA ) >
<!ELEMENT iso14652:Fax ( #PCDATA ) >
<!ELEMENT iso14652:Language ( #PCDATA ) >
<!ELEMENT iso14652:Territory ( #PCDATA ) >
<!ELEMENT iso14652:Audience ( #PCDATA ) >
<!ELEMENT iso14652:Application ( #PCDATA ) >
<!ELEMENT iso14652:Abbreviation ( #PCDATA ) >
<!ELEMENT iso14652:Revision ( #PCDATA ) >
<!ELEMENT iso14652:Date ( #PCDATA ) >

<!ELEMENT iso14652:TelephoneFormat ( iso14652:InternationalPattern| iso14652:DomesticPattern| iso14652:InternationalDialCode| iso14652:InternationalPrefix )* >
<!ELEMENT iso14652:InternationalPattern ( #PCDATA ) >
<!ELEMENT iso14652:DomesticPattern ( #PCDATA ) >
<!ELEMENT iso14652:InternationalDialCode ( #PCDATA ) >
<!ELEMENT iso14652:InternationalPrefix ( #PCDATA ) >

=== svn2github/CLDR/branches/umesh/for-import/external/ibm/main/de_CH.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--add CoreLocaleElements DTD reference here-->
<!-- Tag was "CoreLocaleData" - this has been changed below to allow the
Cupertino XML tool to work -->
<!DOCTYPE localeData SYSTEM "./LocaleElements.dtd" >
<localeData>
<generation date="2002, June, 12"></generation>
<!--
Core Locale Data Format
Version 1.0.4: 2002-05-23
	
Contains locale data elements from ICIR (version 1.4.1) that map into 
CoreLocaleElements.xml.
-->

<!--ICIR VERSION information-->
  <versioning>
    <version number="1.4.1"></version>
  </versioning>

<!--IDENTIFICATION of the locale-->
  <identity>
    <!--Two letter ISO codes only-->
    <language id="de"/>
    <country id="CH"/>
  </identity>

<!--CALENDAR INFORMATION.  Gregorian Only-->
  <calendars>
    <calendar class="Gregorian" default="true">
      <monthNames>
        <month id="1">Januar</month>
        <month id="2">Februar</month>
        <month id="3">M&#x00e4;rz</month>
        <month id="4">April</month>
        <month id="5">Mai</month>
        <month id="6">Juni</month>
        <month id="7">Juli</month>
        <month id="8">August</month>
        <month id="9">September</month>
        <month id="10">Oktober</month>
        <month id="11">November</month>
        <month id="12">Dezember</month>
        <month id="13"></month>
      </monthNames>

      <monthAbbr>
        <month id="1">Jan</month>
        <month id="2">Feb</month>
        <month id="3">M&#x00e4;r</month>
        <month id="4">Apr</month>
        <month id="5">Mai</month>
        <month id="6">Jun</month>
        <month id="7">Jul</month>
        <month id="8">Aug</month>
        <month id="9">Sep</month>
        <month id="10">Okt</month>
        <month id="11">Nov</month>
        <month id="12">Dez</month>
        <month id="13"></month>
      </monthAbbr>

      <dayNames>
        <day id="1">Sonntag</day>
        <day id="2">Montag</day>
        <day id="3">Dienstag</day>
        <day id="4">Mittwoch</day>
        <day id="5">Donnerstag</day>
        <day id="6">Freitag</day>
        <day id="7">Samstag</day>
      </dayNames>

      <dayAbbr>
        <day id="1">So</day>
        <day id="2">Mo</day>
        <day id="3">Di</day>
        <day id="4">Mi</day>
        <day id="5">Do</day>
        <day id="6">Fr</day>
        <day id="7">Sa</day>
      </dayAbbr>

      <!--
      Patterns used for formatting and parsing dates and times for this calendar
      -->

      <patterns>
        <!-- <chars>GyMdhHmsSEDFwWakKz</chars> -->
        <time>
          <full>H:m:s z</full>
          <medium>H:m:s </medium>
          <short>H:m</short>
        </time>

        <date>
          <full>EEEE, d. MMMM yyyy</full>
          <long>d. MMMM yyyy</long>
          <short>dd.MM.yy</short>
        </date>
      </patterns>
    </calendar>
  </calendars>

<!--NUMERIC INFORMATION-->
  <numberFormat class="decimal" default="true">
    <patterns>
      <decimal>#,###,##0.##;-#,###,##0.##</decimal>
    </patterns>
    <symbols>
      <decimal>,</decimal>
      <group>'</group>
      <minusSign>-</minusSign>
    </symbols>
  </numberFormat>

<!--MONETARY INFORMATION-->
  <currencies>
    <!--currency id as per ISO4217, three letter alphabetic code-->
    <currency id="CHF">
      <symbol>CHF</symbol>
      <pattern>&#x00A4; #,###,##0.00;&#x00A4; -#,###,##0.00</pattern>
      <decimal>.</decimal>
      <group>'</group>
    </currency>
  </currencies>

<!--POSIX TYPE INFORMATION-->
  <PosixCompatibilityData>
    <!--POSIX LC_MESSAGE EQUIVALENT-->
    <messages>
      <no>Nein</no>
      <yes>Ja</yes>
      <shortNo>N</shortNo>
      <shortYes>J</shortYes>
    </messages>

    <!--TELEPHONE INFORMATION-->
    <TelephoneFormat>
      <!-- International Access Code is shown below -->
      <InternationalDialCode>00</InternationalDialCode>
    </TelephoneFormat>
  </PosixCompatibilityData>

<!-- Tag was "/CoreLocaleData" - changed below to allow Cupertino XML
tool to work -->
</localeData>

=== svn2github/CLDR/tags/intial-checkin/external/sunjdk/main/it_CH.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE localeData SYSTEM "./LocaleElements.dtd" >

<!-- 
	Copyright (C) 2000-2003, International Business Machines 
	Corporation and others.  All Rights Reserved.
 -->

<localeData>
	<versioning  >
 		<version number="1.0" date="Thu Jun 13 16:04:27 2002">Various notes and changes in version 1.0</version>
	</versioning  >
 	<identity  >
		<country id="CH" />
		<correspondsTo vendor="0810">Windows</correspondsTo>
	</identity  >
	<timeZoneNames>
		<zone id="Africa/Casablanca" default="true">
			<long>
				<generic>GMT</generic>
				<standard>GMT</standard>
			</long>
			<short>
				<generic>Africa/Casablanca</generic>
				<standard>GMT</standard>
				<daylight>GMT</daylight>
			</short>
		</zone>
	</timeZoneNames>
	<calendars>
		<calendar class="gregorian" default="true">
			<patterns> 
				<chars>GuMtkHmsSEDFwWahKz</chars>
				<time>
					<full>H.mm' h' z</full>
					<long>HH:mm:ss z</long>
					<medium>HH:mm:ss</medium>
					<short>HH:mm</short>
				</time>
				<date>
					<full>EEEE, d. MMMM yyyy</full>
					<long>d. MMMM yyyy</long>
					<medium>d-MMM-yy</medium>
					<short>dd.MM.yy</short>
				</date>
 				<dateTime>{1} {0} </dateTime>
			</patterns>
		</calendar>
	</calendars>
	<numberFormat class="decimal" default="true"> 
		<patterns> 
			<decimal>#,##0.###;-#,##0.###</decimal>
			<percent>#,##0%</percent>
		</patterns>
		<symbols>
			<decimal>.</decimal>
			<group>'</group>
			<list>;</list>
			<percentSign>%</percentSign>
			<nativeZeroDigit>0</nativeZeroDigit>
			<patternDigit>#</patternDigit>
			<plusSign>+</plusSign>
			<minusSign>-</minusSign>
			<exponential>E</exponential>
			<perMille>‰</perMille>
			<infinity>∞</infinity>
			<nan>�</nan>
		</symbols>
	</numberFormat> 
	<currencies>
		<currency id="CHF" default="true">
			<symbol>SFr.</symbol>
			<name>CHF</name>
			<decimal>.</decimal>
			<pattern>¤ #,##0.00;¤-#,##0.00</pattern>
		</currency>
	</currencies>

</localeData>

=== svn2github/CLDR/tags/intial-checkin/external/windows/main/ko_KR.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE localeData SYSTEM "./LocaleElements.dtd" >

<!-- 
	Copyright (C) 2000-2003, International Business Machines 
	Corporation and others.  All Rights Reserved.
 -->

<localeData>
	<versioning  >
 		<version number="1.0" date="Tue Jun 11 15:07:00 2002">Various notes and changes in version 1.0</version>
	</versioning  >
 	<identity  >
		<country id="KR" />
		<correspondsTo vendor="0412">Windows</correspondsTo>
	</identity  >
	<calendars>
		<calendar class="gregorian" default="true">
			<monthNames>
				<month id="1">1월</month>
				<month id="2">2월</month>
				<month id="3">3월</month>
				<month id="4">4월</month>
				<month id="5">5월</month>
				<month id="6">6월</month>
				<month id="7">7월</month>
				<month id="8">8월</month>
				<month id="9">9월</month>
				<month id="10">10월</month>
				<month id="11">11월</month>
				<month id="12">12월</month>
				<month id="13"></month>
			</monthNames>
			<dayNames>
				<day id="1">일요일 </day>
				<day id="2">월요일 </day>
				<day id="3">화요일 </day>
				<day id="4">수요일 </day>
				<day id="5">목요일 </day>
				<day id="6">금요일 </day>
				<day id="7">토요일 </day>
			</dayNames>
			<dayAbbr>
				<day id="1">일 </day>
				<day id="2">월 </day>
				<day id="3">화 </day>
				<day id="4">수 </day>
				<day id="5">목 </day>
				<day id="6">금 </day>
				<day id="7">토 </day>
			</dayAbbr>
			<am>오전</am><pm>오후</pm>
			<patterns> 
				<time>
					<full></full>
					<long></long>
					<medium>a h:mm:ss</medium>
					<short></short>
				</time>
				<date>
					<full>yyyy'년' M'월' d'일' dddd</full>
					<long></long>
					<medium></medium>
					<short>yyyy-MM-dd</short>
				</date>
 				<dateTime> </dateTime>
			</patterns>
			<firstDay>6</firstDay>
			<minDays></minDays>
		</calendar>
	</calendars>
	<numberFormat class="decimal" default="true"> 
		<patterns> 
			<decimal></decimal>
			<percent></percent>
		</patterns>
	</numberFormat> 
	<currencies>
		<currency id="KRW" default="true">
			<symbol>₩</symbol>
			<name>KRW</name>
			<decimal>.</decimal>
			<pattern>¤#,##0.00;-¤#,##0.00</pattern>
		</currency>
	</currencies>

</localeData>

=== svn2github/CLDR/branches/maint/maint-1-9/external/ibm/main/pt_PT.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--add CoreLocaleElements DTD reference here-->
<!-- Tag was "CoreLocaleData" - this has been changed below to allow the
Cupertino XML tool to work -->
<!DOCTYPE localeData SYSTEM "./LocaleElements.dtd" >
<localeData>
<generation date="2002, June, 12"></generation>
<!--
Core Locale Data Format
Version 1.0.4: 2002-05-23
	
Contains locale data elements from ICIR (version 1.4.1) that map into 
CoreLocaleElements.xml.
-->

<!--ICIR VERSION information-->
  <versioning>
    <version number="1.4.1"></version>
  </versioning>

<!--IDENTIFICATION of the locale-->
  <identity>
    <!--Two letter ISO codes only-->
    <language id="pt"/>
    <country id="PT"/>
  </identity>

<!--CALENDAR INFORMATION.  Gregorian Only-->
  <calendars>
    <calendar class="Gregorian" default="true">
      <monthNames>
        <month id="1">Janeiro</month>
        <month id="2">Fevereiro</month>
        <month id="3">Mar&#x00e7;o</month>
        <month id="4">Abril</month>
        <month id="5">Maio</month>
        <month id="6">Junho</month>
        <month id="7">Julho</month>
        <month id="8">Agosto</month>
        <month id="9">Setembro</month>
        <month id="10">Outubro</month>
        <month id="11">Novembro</month>
        <month id="12">Dezembro</month>
        <month id="13"></month>
      </monthNames>

      <monthAbbr>
        <month id="1">Jan</month>
        <month id="2">Fev</month>
        <month id="3">Mar</month>
        <month id="4">Abr</month>
        <month id="5">Mai</month>
        <month id="6">Jun</month>
        <month id="7">Jul</month>
        <month id="8">Ago</month>
        <month id="9">Set</month>
        <month id="10">Out</month>
        <month id="11">Nov</month>
        <month id="12">Dez</month>
        <month id="13"></month>
      </monthAbbr>

      <dayNames>
        <day id="1">Domingo</day>
        <day id="2">Segunda&#x002d;feira</day>
        <day id="3">Ter&#x00e7;a&#x002d;feira</day>
        <day id="4">Quarta&#x002d;feira</day>
        <day id="5">Quinta&#x002d;feira</day>
        <day id="6">Sexta&#x002d;feira</day>
        <day id="7">S&#x00e1;bado</day>
      </dayNames>

      <dayAbbr>
        <day id="1">Dom</day>
        <day id="2">Seg</day>
        <day id="3">Ter</day>
        <day id="4">Qua</day>
        <day id="5">Qui</day>
        <day id="6">Sex</day>
        <day id="7">S&#x00E1;b</day>
      </dayAbbr>

      <!--
      Patterns used for formatting and parsing dates and times for this calendar
      -->

      <patterns>
        <!-- <chars>GyMdhHmsSEDFwWakKz</chars> -->
        <time>
          <full>HH:mm:ss</full>
          <medium>HH:mm:ss</medium>
          <short>HH:mm</short>
        </time>

        <date>
          <full>EEEE, d 'de' MMMM 'de' yyyy</full>
          <long>d 'de' MMMM 'de' yyyy</long>
          <short>dd/MM/yyyy</short>
        </date>
      </patterns>
    </calendar>
  </calendars>

<!--NUMERIC INFORMATION-->
  <numberFormat class="decimal" default="true">
    <patterns>
      <decimal>#,###,##0.##;-#,###,##0.##</decimal>
    </patterns>
    <symbols>
      <decimal>,</decimal>
      <group>.</group>
      <minusSign>-</minusSign>
    </symbols>
  </numberFormat>

<!--MONETARY INFORMATION-->
  <currencies>
    <!--currency id as per ISO4217, three letter alphabetic code-->
    <currency id="EUR">
      <symbol>&#x20AC;</symbol>
      <pattern>#,###,##0.00 &#x00A4;;-#,###,##0.00 &#x00A4;</pattern>
      <decimal>$</decimal>
      <group>.</group>
    </currency>
  </currencies>

<!--POSIX TYPE INFORMATION-->
  <PosixCompatibilityData>
    <!--POSIX LC_MESSAGE EQUIVALENT-->
    <messages>
      <no>N&#x00c3;O</no>
      <yes>SIM</yes>
      <shortNo>N</shortNo>
      <shortYes>S</shortYes>
    </messages>

    <!--TELEPHONE INFORMATION-->
    <TelephoneFormat>
      <!-- International Access Code is shown below -->
      <InternationalDialCode>00</InternationalDialCode>
    </TelephoneFormat>
  </PosixCompatibilityData>

<!-- Tag was "/CoreLocaleData" - changed below to allow Cupertino XML
tool to work -->
</localeData>
