=== svn2github/CLDR/trunk/LocaleElements.dtd
<!ELEMENT Abbreviation ( #PCDATA ) >

<!ELEMENT Address ( #PCDATA ) >

<!ELEMENT AddressFormat ( PostalPattern ) >

<!ELEMENT Application ( #PCDATA ) >

<!ELEMENT Audience ( #PCDATA ) >

<!ELEMENT Contact ( #PCDATA ) >

<!ELEMENT CountryCar ( #PCDATA ) >

<!ELEMENT CountryISBNNumber ( #PCDATA ) >

<!ELEMENT CountryNumber ( #PCDATA ) >

<!ELEMENT CountryPost ( #PCDATA ) >

<!ELEMENT Date ( #PCDATA ) >

<!ELEMENT DomesticPattern ( #PCDATA ) >

<!ELEMENT Email ( #PCDATA ) >

<!ELEMENT Fax ( #PCDATA ) >

<!ELEMENT GeneralSalutation ( #PCDATA ) >

<!ELEMENT Height ( #PCDATA ) >

<!ELEMENT Identification ( Title| Source| Address| Contact| Email| Telephone| Fax| Language| Territory| Audience| Application| Abbreviation| Revision| Date )* >

<!ELEMENT InternationalDialCode ( #PCDATA ) >

<!ELEMENT InternationalPattern ( #PCDATA ) >

<!ELEMENT InternationalPrefix ( #PCDATA ) >

<!ELEMENT Language ( #PCDATA ) >

<!ELEMENT LanguageLibraryUse ( #PCDATA ) >

<!ELEMENT LongSalutationMiss ( #PCDATA ) >

<!ELEMENT LongSalutationMr ( #PCDATA ) >

<!ELEMENT LongSalutationMrs ( #PCDATA ) >

<!ELEMENT NameFormat ( NamePattern| GeneralSalutation| ShortSalutationMr| ShortSalutationMiss|ShortSalutationMrs| LongSalutationMr| LongSalutationMiss| LongSalutationMrs )* >

<!ELEMENT NamePattern ( #PCDATA ) >

<!ELEMENT PaperSize ( Height, Width, Units ) >

<!ELEMENT PosixCompatibilityData ( messages| AddressFormat| NameFormat| Identification| TelephoneFormat )* >

<!ELEMENT PostalPattern ( #PCDATA ) >

<!ELEMENT Revision ( #PCDATA ) >

<!ELEMENT ShortSalutationMiss ( #PCDATA ) >

<!ELEMENT ShortSalutationMr ( #PCDATA ) >

<!ELEMENT ShortSalutationMrs ( #PCDATA ) >

<!ELEMENT Source ( #PCDATA ) >

<!ELEMENT Telephone ( #PCDATA ) >

<!ELEMENT TelephoneFormat ( InternationalPattern| DomesticPattern| InternationalDialCode| InternationalPrefix )* >

<!ELEMENT Territory ( #PCDATA ) >

<!ELEMENT Title ( #PCDATA ) >

<!ELEMENT Units ( #PCDATA ) >

<!ELEMENT Width ( #PCDATA ) >

<!ELEMENT after ( #PCDATA ) >

<!ELEMENT normalization ( #PCDATA ) >

<!ELEMENT alternate ( #PCDATA ) >

<!ELEMENT vairableTop ( #PCDATA ) >

<!ELEMENT caseLevel ( #PCDATA ) >

<!ELEMENT caseFirst ( #PCDATA ) >

<!ELEMENT composition ( #PCDATA ) >

<!ELEMENT lt1 ( #PCDATA ) >

<!ELEMENT am ( #PCDATA ) >

<!ELEMENT boundaries ( grapheme| word| Sentence| Line )* >

<!ELEMENT TransliteratorNamePattern ( #PCDATA ) >

<!ELEMENT calendar ( am | dayAbbr | dayNames | eras | monthAbbr | monthNames | patterns | pm | week |firstDay |minDays )* >
<!ATTLIST calendar class NMTOKEN #REQUIRED >
<!ATTLIST calendar default NMTOKEN #IMPLIED >
<!ATTLIST calendar inheritsFrom NMTOKEN #IMPLIED >

<!ELEMENT calendars ( calendar+ ) >

<!ELEMENT chars ( #PCDATA ) >

<!ELEMENT city ( #PCDATA ) >

<!ELEMENT collation ( collationElements ) >
<!ATTLIST collation accentOrder NMTOKEN #REQUIRED >
<!ATTLIST collation override NMTOKEN #REQUIRED >
<!ATTLIST collation version NMTOKEN #REQUIRED >


<!ELEMENT collationElements ( after | eq | gt1 | gt2 | gt3 | normalization | alternate | vairableTop | caseLevel | caseFirst | lt1)* >

<!ELEMENT correspondsTo ( #PCDATA ) >
<!ATTLIST correspondsTo vendor NMTOKEN #REQUIRED >

<!ELEMENT countries ( country+ ) >

<!ELEMENT country ( #PCDATA ) >
<!ATTLIST country id NMTOKEN #REQUIRED >
<!ATTLIST country iso2 NMTOKEN #IMPLIED >
<!ATTLIST country iso3 NMTOKEN #IMPLIED >

<!ELEMENT currencies ( currency+ ) >

<!ELEMENT currency ( symbol| pattern| decimal| name |group )* >
<!ATTLIST currency default NMTOKEN #IMPLIED >
<!ATTLIST currency id NMTOKEN #REQUIRED >

<!ELEMENT name ( #PCDATA ) >

<!ELEMENT date ( full| long| medium| short )* >

<!ELEMENT dateTime ( #PCDATA ) >

<!ELEMENT day ( #PCDATA ) >
<!ATTLIST day id NMTOKEN #IMPLIED >

<!ELEMENT dayAbbr ( day+ ) >

<!ELEMENT dayNames ( day+ ) >

<!ELEMENT daylight ( #PCDATA ) >

<!ELEMENT decimal ( #PCDATA ) >

<!ELEMENT displayNames ( scripts| languages| countries| variants |localePatterns )* >

<!ELEMENT encodings ( mapping+ ) >
<!ATTLIST encodings requiredLetters NMTOKEN #REQUIRED >

<!ELEMENT eq ( #PCDATA ) >

<!ELEMENT era ( #PCDATA ) >
<!ATTLIST era id NMTOKEN #REQUIRED >

<!ELEMENT eras ( era+ ) >

<!ELEMENT exponential ( #PCDATA ) >

<!ELEMENT firstDay ( #PCDATA ) >

<!ELEMENT full ( #PCDATA ) >

<!ELEMENT generic ( #PCDATA ) >

<!ELEMENT grapheme ( #PCDATA ) >
<!ATTLIST grapheme class NMTOKEN #REQUIRED >

<!ELEMENT group ( #PCDATA ) >

<!ELEMENT gt1 ( #PCDATA ) >

<!ELEMENT gt2 ( #PCDATA ) >

<!ELEMENT gt3 ( #PCDATA ) >

<!ELEMENT identity ( language| country| variant| correspondsTo )* >

<!ELEMENT infinity ( #PCDATA ) >

<!ELEMENT language ( #PCDATA ) >
<!ATTLIST language id NMTOKEN #REQUIRED >
<!ATTLIST language iso2 NMTOKEN #IMPLIED >
<!ATTLIST language iso3 NMTOKEN #IMPLIED >

<!ELEMENT languages ( language+ ) >

<!ELEMENT list ( #PCDATA ) >

<!ELEMENT locale ( #PCDATA ) >

<!ELEMENT localeData ( versioning | identity| orientation| encodings| displayNames | calendars | numberFormat | currencies | collation | timeZoneNames | boundaries | measurement | CountryPost | CountryNumber | CountryCar | CountryISBNNumber | LanguageLibraryUse | PaperSize | PosixCompatibilityData|TransliteratorNamePattern )* >

<!ELEMENT localePatterns ( locale, list, composition ) >

<!ELEMENT long ( #PCDATA | daylight | generic | standard )* >

<!ELEMENT mapping ( #PCDATA ) >
<!ATTLIST mapping name NMTOKEN #REQUIRED >

<!ELEMENT measurement ( #PCDATA ) >

<!ELEMENT medium ( #PCDATA ) >

<!ELEMENT messages ( no| yes| shortYes| shortNo )* >

<!ELEMENT minDays ( #PCDATA ) >

<!ELEMENT minusSign ( #PCDATA ) >

<!ELEMENT month ( #PCDATA ) >
<!ATTLIST month id NMTOKEN #REQUIRED >

<!ELEMENT monthAbbr ( month+ ) >

<!ELEMENT monthNames ( month+ ) >

<!ELEMENT nan ( #PCDATA ) >

<!ELEMENT nativeZeroDigit ( #PCDATA ) >

<!ELEMENT no ( #PCDATA ) >

<!ELEMENT numberFormat ( patterns| symbols )* >
<!ATTLIST numberFormat class NMTOKEN #REQUIRED >
<!ATTLIST numberFormat default NMTOKEN #REQUIRED >

<!ELEMENT orientation ( #PCDATA ) >
<!ATTLIST orientation characters NMTOKEN #REQUIRED >
<!ATTLIST orientation lines NMTOKEN #REQUIRED >

<!ELEMENT pattern ( #PCDATA ) >

<!ELEMENT patternDigit ( #PCDATA ) >

<!ELEMENT patterns ( chars| time| date| dateTime?| decimal?| percent?| scientific? )* >

<!ELEMENT perMille ( #PCDATA ) >

<!ELEMENT percent ( #PCDATA ) >

<!ELEMENT percentSign ( #PCDATA ) >

<!ELEMENT plusSign ( #PCDATA ) >

<!ELEMENT pm ( #PCDATA ) >

<!ELEMENT scientific ( #PCDATA ) >

<!ELEMENT script ( #PCDATA ) >
<!ATTLIST script id NMTOKEN #REQUIRED >

<!ELEMENT scripts ( script+ ) >

<!ELEMENT short ( #PCDATA | daylight | generic | standard )* >

<!ELEMENT shortNo ( #PCDATA ) >

<!ELEMENT shortYes ( #PCDATA ) >

<!ELEMENT standard ( #PCDATA ) >

<!ELEMENT symbol ( #PCDATA ) >

<!ELEMENT symbols ( decimal, group, list, percentSign, nativeZeroDigit, patternDigit, plusSign, minusSign, exponential, perMille, infinity, nan )* >

<!ELEMENT time ( #PCDATA | full | long | medium | short )* >

<!ELEMENT timeZoneNames ( zone+ ) >

<!ELEMENT variant ( #PCDATA ) >
<!ATTLIST variant id NMTOKEN #REQUIRED >

<!ELEMENT variants ( variant ) >

<!ELEMENT version ( #PCDATA ) >
<!ATTLIST version date CDATA #IMPLIED>
<!ATTLIST version number NMTOKEN #REQUIRED >

<!ELEMENT versioning ( version+ ) >

<!ELEMENT week ( minDays, firstDay, weekendStart, weekendEnd ) >

<!ELEMENT weekendEnd ( day, time ) >

<!ELEMENT weekendStart ( day, time ) >

<!ELEMENT word ( #PCDATA ) >
<!ATTLIST word class NMTOKEN #REQUIRED >

<!ELEMENT Line ( #PCDATA ) >
<!ATTLIST Line class NMTOKEN #REQUIRED >

<!ELEMENT Sentence ( #PCDATA ) >
<!ATTLIST Sentence class NMTOKEN #REQUIRED >

<!ELEMENT yes ( #PCDATA ) >

<!ELEMENT zone ( city | long | short )* >
<!ATTLIST zone default NMTOKEN #IMPLIED >
<!ATTLIST zone id CDATA #REQUIRED >
<!ELEMENT iso14652:iso14652  ( iso14652:messages| iso14652:AddressFormat| iso14652:NameFormat| iso14652:Identification| iso14652:TelephoneFormat )* >

<!ELEMENT iso14652:messages ( iso14652:no| iso14652:yes| iso14652:shortYes| iso14652:shortNo )* >
<!ELEMENT iso14652:no ( #PCDATA ) >
<!ELEMENT iso14652:yes ( #PCDATA ) >
<!ELEMENT iso14652:shortYes ( #PCDATA ) >
<!ELEMENT iso14652:shortNo ( #PCDATA ) >

<!ELEMENT iso14652:AddressFormat ( iso14652:PostalPattern ) >
<!ELEMENT iso14652:PostalPattern ( #PCDATA ) >

<!ELEMENT iso14652:NameFormat ( iso14652:NamePattern| iso14652:GeneralSalutation| iso14652:ShortSalutationMr| iso14652:ShortSalutationMiss|iso14652:ShortSalutationMrs| iso14652:LongSalutationMr| iso14652:LongSalutationMiss| iso14652:LongSalutationMrs )* >
<!ELEMENT iso14652:NamePattern ( #PCDATA ) >
<!ELEMENT iso14652:GeneralSalutation ( #PCDATA ) >
<!ELEMENT iso14652:ShortSalutationMr ( #PCDATA ) >
<!ELEMENT iso14652:ShortSalutationMiss ( #PCDATA ) >
<!ELEMENT iso14652:ShortSalutationMrs ( #PCDATA ) >
<!ELEMENT iso14652:LongSalutationMr ( #PCDATA ) >
<!ELEMENT iso14652:LongSalutationMiss ( #PCDATA ) >
<!ELEMENT iso14652:LongSalutationMrs ( #PCDATA ) >

<!ELEMENT iso14652:Identification ( iso14652:Title| iso14652:Source| iso14652:Address| iso14652:Contact| iso14652:Email| iso14652:Telephone| iso14652:Fax| iso14652:Language| iso14652:Territory| iso14652:Audience| iso14652:Application| iso14652:Abbreviation| iso14652:Revision| iso14652:Date )* >
<!ELEMENT iso14652:Title ( #PCDATA ) >
<!ELEMENT iso14652:Source ( #PCDATA ) >
<!ELEMENT iso14652:Address ( #PCDATA ) >
<!ELEMENT iso14652:Contact ( #PCDATA ) >
<!ELEMENT iso14652:Email ( #PCDATA ) >
<!ELEMENT iso14652:Telephone ( #PCDATA ) >
<!ELEMENT iso14652:Fax ( #PCDATA ) >
<!ELEMENT iso14652:Language ( #PCDATA ) >
<!ELEMENT iso14652:Territory ( #PCDATA ) >
<!ELEMENT iso14652:Audience ( #PCDATA ) >
<!ELEMENT iso14652:Application ( #PCDATA ) >
<!ELEMENT iso14652:Abbreviation ( #PCDATA ) >
<!ELEMENT iso14652:Revision ( #PCDATA ) >
<!ELEMENT iso14652:Date ( #PCDATA ) >

<!ELEMENT iso14652:TelephoneFormat ( iso14652:InternationalPattern| iso14652:DomesticPattern| iso14652:InternationalDialCode| iso14652:InternationalPrefix )* >
<!ELEMENT iso14652:InternationalPattern ( #PCDATA ) >
<!ELEMENT iso14652:DomesticPattern ( #PCDATA ) >
<!ELEMENT iso14652:InternationalDialCode ( #PCDATA ) >
<!ELEMENT iso14652:InternationalPrefix ( #PCDATA ) >

=== svn2github/CLDR/trunk/external/windows/main/fr_LU.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE localeData SYSTEM "./LocaleElements.dtd" >

<!-- 
	Copyright (C) 2000-2003, International Business Machines 
	Corporation and others.  All Rights Reserved.
 -->

<localeData>
	<versioning  >
 		<version number="1.0" date="Tue Jun 11 15:06:59 2002">Various notes and changes in version 1.0</version>
	</versioning  >
 	<identity  >
		<country id="LU" />
		<correspondsTo vendor="140C">Windows</correspondsTo>
	</identity  >
	<calendars>
		<calendar class="gregorian" default="true">
			<monthNames>
				<month id="1">janvier</month>
				<month id="2">février</month>
				<month id="3">mars</month>
				<month id="4">avril</month>
				<month id="5">mai</month>
				<month id="6">juin</month>
				<month id="7">juillet</month>
				<month id="8">août</month>
				<month id="9">septembre</month>
				<month id="10">octobre</month>
				<month id="11">novembre</month>
				<month id="12">décembre</month>
				<month id="13"></month>
			</monthNames>
			<dayNames>
				<day id="1">dimanche </day>
				<day id="2">lundi </day>
				<day id="3">mardi </day>
				<day id="4">mercredi </day>
				<day id="5">jeudi </day>
				<day id="6">vendredi </day>
				<day id="7">samedi </day>
			</dayNames>
			<dayAbbr>
				<day id="1">dim. </day>
				<day id="2">lun. </day>
				<day id="3">mar. </day>
				<day id="4">mer. </day>
				<day id="5">jeu. </day>
				<day id="6">ven. </day>
				<day id="7">sam. </day>
			</dayAbbr>
			<am></am><pm></pm>
			<patterns> 
				<time>
					<full></full>
					<long></long>
					<medium>HH:mm:ss</medium>
					<short></short>
				</time>
				<date>
					<full>dddd d MMMM yyyy</full>
					<long></long>
					<medium></medium>
					<short>dd/MM/yyyy</short>
				</date>
 				<dateTime> </dateTime>
			</patterns>
			<firstDay>0</firstDay>
			<minDays></minDays>
		</calendar>
	</calendars>
	<numberFormat class="decimal" default="true"> 
		<patterns> 
			<decimal></decimal>
			<percent></percent>
		</patterns>
		<symbols>
			<decimal>,</decimal>
			<group> </group>
			<list>;</list>
			<percentSign>%</percentSign>
			<nativeZeroDigit>;</nativeZeroDigit>
			<patternDigit>#</patternDigit>
			<plusSign>+</plusSign>
			<minusSign>-</minusSign>
			<exponential>E</exponential>
			<perMille>‰</perMille>
			<infinity>∞</infinity>
			<nan>�</nan>
		</symbols>
	</numberFormat> 
	<currencies>
		<currency id="LUF" default="true">
			<symbol>F</symbol>
			<name>LUF</name>
			<decimal>,</decimal>
			<pattern>#,##0.00 ¤;-#,##0.00 ¤</pattern>
		</currency>
	</currencies>

</localeData>

=== svn2github/CLDR/branches/srl/r2358alt/external/ibm/main/zh_CN.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--add CoreLocaleElements DTD reference here-->
<!-- Tag was "CoreLocaleData" - this has been changed below to allow the
Cupertino XML tool to work -->
<!DOCTYPE localeData SYSTEM "./LocaleElements.dtd" >
<localeData>
<generation date="2002, June, 12"></generation>
<!--
Core Locale Data Format
Version 1.0.4: 2002-05-23
	
Contains locale data elements from ICIR (version 1.4.1) that map into 
CoreLocaleElements.xml.
-->

<!--ICIR VERSION information-->
  <versioning>
    <version number="1.4.1"></version>
  </versioning>

<!--IDENTIFICATION of the locale-->
  <identity>
    <!--Two letter ISO codes only-->
    <language id="zh"/>
    <country id="CN"/>
  </identity>

<!--CALENDAR INFORMATION.  Gregorian Only-->
  <calendars>
    <calendar class="Gregorian" default="true">
      <monthNames>
        <month id="1">1&#x6708;</month>
        <month id="2">2&#x6708;</month>
        <month id="3">3&#x6708;</month>
        <month id="4">4&#x6708;</month>
        <month id="5">5&#x6708;</month>
        <month id="6">6&#x6708;</month>
        <month id="7">7&#x6708;</month>
        <month id="8">8&#x6708;</month>
        <month id="9">9&#x6708;</month>
        <month id="10">10&#x6708;</month>
        <month id="11">11&#x6708;</month>
        <month id="12">12&#x6708;</month>
        <month id="13"></month>
      </monthNames>

      <monthAbbr>
        <month id="1">1&#x6708;</month>
        <month id="2">2&#x6708;</month>
        <month id="3">3&#x6708;</month>
        <month id="4">4&#x6708;</month>
        <month id="5">5&#x6708;</month>
        <month id="6">6&#x6708;</month>
        <month id="7">7&#x6708;</month>
        <month id="8">8&#x6708;</month>
        <month id="9">9&#x6708;</month>
        <month id="10">10&#x6708;</month>
        <month id="11">11&#x6708;</month>
        <month id="12">12&#x6708;</month>
        <month id="13"></month>
      </monthAbbr>

      <dayNames>
        <day id="1">&#x661f;&#x671f;&#x65e5;</day>
        <day id="2">&#x661f;&#x671f;&#x4e00;</day>
        <day id="3">&#x661f;&#x671f;&#x4e8c;</day>
        <day id="4">&#x661f;&#x671f;&#x4e09;</day>
        <day id="5">&#x661f;&#x671f;&#x56db;</day>
        <day id="6">&#x661f;&#x671f;&#x4e94;</day>
        <day id="7">&#x661f;&#x671f;&#x516d;</day>
      </dayNames>

      <dayAbbr>
        <day id="1">&#x661f;&#x671f;&#x65e5;</day>
        <day id="2">&#x661f;&#x671f;&#x4e00;</day>
        <day id="3">&#x661f;&#x671f;&#x4e8c;</day>
        <day id="4">&#x661f;&#x671f;&#x4e09;</day>
        <day id="5">&#x661f;&#x671f;&#x56db;</day>
        <day id="6">&#x661f;&#x671f;&#x4e94;</day>
        <day id="7">&#x661f;&#x671f;&#x516d;</day>
      </dayAbbr>

      <!--
      Patterns used for formatting and parsing dates and times for this calendar
      -->

      <patterns>
        <!-- <chars>GyMdhHmsSEDFwWakKz</chars> -->
        <time>
          <full>H'&#x65f6;'m'&#x5206;'s'&#x79d2;'</full>
          <medium>H:m:s</medium>
          <short>H:m</short>
        </time>

        <date>
          <full>yyyy'&#x5e74;'MMMMd'&#x65e5;' EEEE</full>
          <long>yyyy'&#x5e74;'MMMMd'&#x65e5;'</long>
          <short>yy-M-d</short>
        </date>
      </patterns>
    </calendar>
  </calendars>

<!--NUMERIC INFORMATION-->
  <numberFormat class="decimal" default="true">
    <patterns>
      <decimal>#,###,##0.##;-#,###,##0.##</decimal>
    </patterns>
    <symbols>
      <decimal>.</decimal>
      <group>,</group>
      <minusSign>-</minusSign>
    </symbols>
  </numberFormat>

<!--MONETARY INFORMATION-->
  <currencies>
    <!--currency id as per ISO4217, three letter alphabetic code-->
    <currency id="CNY">
      <symbol>&#xffe5;</symbol>
      <pattern>&#x00A4;#,###,##0;-&#x00A4;#,###,##0</pattern>
      <decimal>.</decimal>
      <group>,</group>
    </currency>
  </currencies>

<!--POSIX TYPE INFORMATION-->
  <PosixCompatibilityData>
    <!--POSIX LC_MESSAGE EQUIVALENT-->
    <messages>
      <no>&#x5426;</no>
      <yes>&#x662f;</yes>
      <shortNo>&#x5426;</shortNo>
      <shortYes>&#x662f;</shortYes>
    </messages>

    <!--TELEPHONE INFORMATION-->
    <TelephoneFormat>
      <!-- International Access Code is shown below -->
      <InternationalDialCode>00</InternationalDialCode>
    </TelephoneFormat>
  </PosixCompatibilityData>

<!-- Tag was "/CoreLocaleData" - changed below to allow Cupertino XML
tool to work -->
</localeData>

=== svn2github/CLDR/branches/umesh/collation/external/ibm/main/sq_AL.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--add CoreLocaleElements DTD reference here-->
<!-- Tag was "CoreLocaleData" - this has been changed below to allow the
Cupertino XML tool to work -->
<!DOCTYPE localeData SYSTEM "./LocaleElements.dtd" >
<localeData>
<generation date="2002, June, 12"></generation>
<!--
Core Locale Data Format
Version 1.0.4: 2002-05-23
	
Contains locale data elements from ICIR (version 1.4.1) that map into 
CoreLocaleElements.xml.
-->

<!--ICIR VERSION information-->
  <versioning>
    <version number="1.4.1"></version>
  </versioning>

<!--IDENTIFICATION of the locale-->
  <identity>
    <!--Two letter ISO codes only-->
    <language id="sq"/>
    <country id="AL"/>
  </identity>

<!--CALENDAR INFORMATION.  Gregorian Only-->
  <calendars>
    <calendar class="Gregorian" default="true">
      <monthNames>
        <month id="1">janar</month>
        <month id="2">shkurt</month>
        <month id="3">mars</month>
        <month id="4">prill</month>
        <month id="5">maj</month>
        <month id="6">qershor</month>
        <month id="7">korrik</month>
        <month id="8">gusht</month>
        <month id="9">shtator</month>
        <month id="10">tetor</month>
        <month id="11">n&#x00eb;ntor</month>
        <month id="12">dhjetor</month>
        <month id="13"></month>
      </monthNames>

      <monthAbbr>
        <month id="1">Jan</month>
        <month id="2">Shk</month>
        <month id="3">Mar</month>
        <month id="4">Pri</month>
        <month id="5">Maj</month>
        <month id="6">Qer</month>
        <month id="7">Kor</month>
        <month id="8">Gsh</month>
        <month id="9">Sht</month>
        <month id="10">Tet</month>
        <month id="11">N&#x00eb;n</month>
        <month id="12">Dhj</month>
        <month id="13"></month>
      </monthAbbr>

      <dayNames>
        <day id="1">e diel&#x00eb;</day>
        <day id="2">e h&#x00eb;n&#x00eb;</day>
        <day id="3">e mart&#x00eb;</day>
        <day id="4">e m&#x00eb;rkur&#x00eb;</day>
        <day id="5">e enjte</day>
        <day id="6">e premte</day>
        <day id="7">e shtun&#x00eb;</day>
      </dayNames>

      <dayAbbr>
        <day id="1">Die</day>
        <day id="2">H&#x00eb;n</day>
        <day id="3">Mar</day>
        <day id="4">M&#x00eb;r</day>
        <day id="5">Enj</day>
        <day id="6">Pre</day>
        <day id="7">Sht</day>
      </dayAbbr>

      <!--
      Patterns used for formatting and parsing dates and times for this calendar
      -->

      <patterns>
        <!-- <chars>GyMdhHmsSEDFwWakKz</chars> -->
        <time>
          <full>HH:mm:ss</full>
          <medium>HH:mm:ss</medium>
          <short>HH:mm</short>
        </time>

        <date>
          <full>EEEE, dd MMMM yyyy</full>
          <long>dd MMMM yyyy</long>
          <short>dd-MM-yy</short>
        </date>
      </patterns>
    </calendar>
  </calendars>

<!--NUMERIC INFORMATION-->
  <numberFormat class="decimal" default="true">
    <patterns>
      <decimal>#,###,##0.##;-#,###,##0.##</decimal>
    </patterns>
    <symbols>
      <decimal>,</decimal>
      <group>.</group>
      <minusSign>-</minusSign>
    </symbols>
  </numberFormat>

<!--MONETARY INFORMATION-->
  <currencies>
    <!--currency id as per ISO4217, three letter alphabetic code-->
    <currency id="ALL">
      <symbol>Lek</symbol>
      <pattern>&#x00A4;#,###,##0.00;-&#x00A4;#,###,##0.00</pattern>
      <decimal>,</decimal>
      <group>.</group>
    </currency>
  </currencies>

<!--POSIX TYPE INFORMATION-->
  <PosixCompatibilityData>
    <!--POSIX LC_MESSAGE EQUIVALENT-->
    <messages>
      <no>JO</no>
      <yes>PO</yes>
      <shortNo>JO</shortNo>
      <shortYes>PO</shortYes>
    </messages>

    <!--TELEPHONE INFORMATION-->
    <TelephoneFormat>
      <!-- International Access Code is shown below -->
      <InternationalDialCode>00</InternationalDialCode>
    </TelephoneFormat>
  </PosixCompatibilityData>

<!-- Tag was "/CoreLocaleData" - changed below to allow Cupertino XML
tool to work -->
</localeData>

=== svn2github/CLDR/trunk/external/ibmjdk/main/fr_CA.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE localeData SYSTEM "./LocaleElements.dtd" >

<!-- 
	Copyright (C) 2000-2003, International Business Machines 
	Corporation and others.  All Rights Reserved.
 -->

<localeData>
	<versioning  >
 		<version number="1.0" date="Thu Jun 13 16:05:09 2002">Various notes and changes in version 1.0</version>
	</versioning  >
 	<identity  >
		<country id="CA" />
		<correspondsTo vendor="0c0c">Windows</correspondsTo>
	</identity  >

	<displayNames >
		<countries  >
			<country id="US">Ã‰tats-Unis</country>
		</countries  >

	</displayNames >
	<calendars>
		<calendar class="gregorian" default="true">
			<patterns> 
				<chars>GanjkHmsSEDFwWxhKzZ</chars>
				<time>
					<full>H' h 'mm z</full>
					<long>HH:mm:ss z</long>
					<medium>HH:mm:ss</medium>
					<short>HH:mm</short>
				</time>
				<date>
					<full>EEEE d MMMM yyyy</full>
					<long>d MMMM yyyy</long>
					<medium>yyyy-MM-dd</medium>
					<short>yy-MM-dd</short>
				</date>
 				<dateTime>{1} {0} </dateTime>
			</patterns>
		</calendar>
	</calendars>
	<numberFormat class="decimal" default="true"> 
		<patterns> 
			<decimal>#,##0.###;-#,##0.###</decimal>
			<percent>#,##0%</percent>
		</patterns>
	</numberFormat> 

</localeData>

=== svn2github/CLDR/tags/intial-checkin/external/windows/main/be_BY.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE localeData SYSTEM "./LocaleElements.dtd" >

<!-- 
	Copyright (C) 2000-2003, International Business Machines 
	Corporation and others.  All Rights Reserved.
 -->

<localeData>
	<versioning  >
 		<version number="1.0" date="Tue Jun 11 15:06:53 2002">Various notes and changes in version 1.0</version>
	</versioning  >
 	<identity  >
		<country id="BY" />
		<correspondsTo vendor="0423">Windows</correspondsTo>
	</identity  >
	<calendars>
		<calendar class="gregorian" default="true">
			<monthNames>
				<month id="1">Студзень</month>
				<month id="2">Люты</month>
				<month id="3">Сакавік</month>
				<month id="4">Красавік</month>
				<month id="5">Май</month>
				<month id="6">Чэрвень</month>
				<month id="7">Ліпень</month>
				<month id="8">Жнівень</month>
				<month id="9">Верасень</month>
				<month id="10">Кастрычнік</month>
				<month id="11">Лістапад</month>
				<month id="12">Снежань</month>
				<month id="13"></month>
			</monthNames>
			<dayNames>
				<day id="1">нядзеля </day>
				<day id="2">панядзелак </day>
				<day id="3">аўторак </day>
				<day id="4">серада </day>
				<day id="5">чацвер </day>
				<day id="6">пятніца </day>
				<day id="7">субота </day>
			</dayNames>
			<dayAbbr>
				<day id="1">нд </day>
				<day id="2">пн </day>
				<day id="3">аў </day>
				<day id="4">ср </day>
				<day id="5">чц </day>
				<day id="6">пт </day>
				<day id="7">сб </day>
			</dayAbbr>
			<am></am><pm></pm>
			<patterns> 
				<time>
					<full></full>
					<long></long>
					<medium>H:mm:ss</medium>
					<short></short>
				</time>
				<date>
					<full>d MMMM yyyy</full>
					<long></long>
					<medium></medium>
					<short>dd.MM.yyyy</short>
				</date>
 				<dateTime> </dateTime>
			</patterns>
			<firstDay>0</firstDay>
			<minDays></minDays>
		</calendar>
	</calendars>
	<numberFormat class="decimal" default="true"> 
		<patterns> 
			<decimal></decimal>
			<percent></percent>
		</patterns>
	</numberFormat> 
	<currencies>
		<currency id="BYB" default="true">
			<symbol>р.</symbol>
			<name>BYB</name>
			<decimal>,</decimal>
		</currency>
	</currencies>

</localeData>

=== svn2github/CLDR/tags/intial-checkin/external/windows/main/nl_NL.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE localeData SYSTEM "./LocaleElements.dtd" >

<!-- 
	Copyright (C) 2000-2003, International Business Machines 
	Corporation and others.  All Rights Reserved.
 -->

<localeData>
	<versioning  >
 		<version number="1.0" date="Tue Jun 11 15:07:01 2002">Various notes and changes in version 1.0</version>
	</versioning  >
 	<identity  >
		<country id="NL" />
		<correspondsTo vendor="0413">Windows</correspondsTo>
	</identity  >
	<calendars>
		<calendar class="gregorian" default="true">
			<monthNames>
				<month id="1">januari</month>
				<month id="2">februari</month>
				<month id="3">maart</month>
				<month id="4">april</month>
				<month id="5">mei</month>
				<month id="6">juni</month>
				<month id="7">juli</month>
				<month id="8">augustus</month>
				<month id="9">september</month>
				<month id="10">oktober</month>
				<month id="11">november</month>
				<month id="12">december</month>
				<month id="13"></month>
			</monthNames>
			<dayNames>
				<day id="1">zondag </day>
				<day id="2">maandag </day>
				<day id="3">dinsdag </day>
				<day id="4">woensdag </day>
				<day id="5">donderdag </day>
				<day id="6">vrijdag </day>
				<day id="7">zaterdag </day>
			</dayNames>
			<dayAbbr>
				<day id="1">zo </day>
				<day id="2">ma </day>
				<day id="3">di </day>
				<day id="4">wo </day>
				<day id="5">do </day>
				<day id="6">vr </day>
				<day id="7">za </day>
			</dayAbbr>
			<am></am><pm></pm>
			<patterns> 
				<time>
					<full></full>
					<long></long>
					<medium>H:mm:ss</medium>
					<short></short>
				</time>
				<date>
					<full>dddd d MMMM yyyy</full>
					<long></long>
					<medium></medium>
					<short>d-M-yyyy</short>
				</date>
 				<dateTime> </dateTime>
			</patterns>
			<firstDay>0</firstDay>
			<minDays></minDays>
		</calendar>
	</calendars>
	<numberFormat class="decimal" default="true"> 
		<patterns> 
			<decimal></decimal>
			<percent></percent>
		</patterns>
	</numberFormat> 
	<currencies>
		<currency id="NLG" default="true">
			<symbol>fl</symbol>
			<name>NLG</name>
			<decimal>,</decimal>
		</currency>
	</currencies>

</localeData>
